routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('home', function () {
    return view('home');
});

Route::resource('pozivi', 'PoziviKontroler');




Route::resource('pitanjapoziv', 'PitanjaPoziviKontroler');





// Projekat rute


// Vrsi se filter pretraga projekata
Route::post('/projekatpretraga', 'ProjekatKontroler@pretragaProjakata');


Route::resource('projekat', 'ProjekatKontroler');


Route::resource('recenzent', 'RecenzentKontroler');

Route::resource('recenzentadmin', 'RecenzentAdminKontroler');

Route::resource('ocenjivanjeprojekta', 'RecenzentOcenjivanjeProjektaKontroler');

Route::resource('adminanketa', 'AdminAnketaKontroler');

Route::resource('recenzentanketa', 'RecenzentAnketaKontrolor');

Route::resource('adminobavestenja', 'AdminObavestenjaKontroler');

Auth::routes();

app/Poziv.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Poziv extends Model
{
 protected $guarded = [];
  // Table Name
  protected $table = 'pozivi';
  // Primary Key
  public $primaryKey = 'idPoziv';

 public function pitanja()
    {
       return $this->hasMany('App\PitanjaPoziv', 'pozivi_idPoziv', 'idPoziv');
    }

     public function projekat()
    {
       return $this->hasMany('App\Projekat', 'pozivi_idPoziv', 'idPoziv');
    }
  }

resources/views/poziv/pozivi.blade.php
@extends('basic')
@section('content')
<div class="row">
  <div class="col-4 offset-4 mt-5">
     {{ Form::open(array('url' => 'pozivi')) }}
      <div class="form-group">
           {{Form::label('naziv', 'Poziv')}}
           {{Form::text('naziv', '', ['class' => 'form-control', 'placeholder'=>'Unesite poziv'])}}
      </div>
      <div class="">
          {{Form::submit('Dodaj',['class' => 'btn dugme'] )}}
      </div>
    {{ Form::close() }}
  </div>
</div>
<div class="row">
    <div class="offset-1  col-sm-2 col-11">
      @foreach($pozivi as $poziv)
        <div class="row card card-body mb-2" onclick="prikazi({{$poziv->idPoziv}})">
            <div>
                <p>{{$poziv->naziv}}</p>
            </div>
           </div>
    @endforeach
    </div>

    <div class="col-sm-8 col-12" style="margin-right: 5px;">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
         <div id="projekat">

         </div>
     </div>
 </div>


@endsection

resources/views/poziv/pozivi_detalji.blade.php
<div class="offset-1 col-10 offset-1 mt-2">
    

        <div class="form-group row">

                        <input type="text" name="pitanje" id="pitanje" class="form-control" placeholder="Unesi pitanje" />
                  
         
        </div>
          <div class="form-group row">
       <input type="hidden" id="idPoziv" value="{{$pitanja->idPoziv}}" />

            <button type="submit" class="btn" onclick='dodajPitanje()'>Dodaj</button>
        </div>

    </div>
<div class="row" >
 <div class="offset-3 col-md-6 col-12 offset-3">
   <table class="table table-responsive"> 
       @if($poziv)
       @foreach($poziv as $p)
       <tr>
           <td>
              <textarea class="form-control" disabled>{{$p->pitanje}}</textarea>  

            </td>
            <td>
                {{--<form method="POST" action="{{ route('pitanjapoziv.destroy', $p->idPitanja) }}">--}}

                    {{--<button type="submit" class="btn dugme">Obrisi</button>--}}

                {{--</form>--}}

          <button type="submit" class="btn btn-sm dugme" onclick='obrisi({{$p->idPitanja}})'>Obrisi</button>

            </td>
           </td>
       </tr>
      @endforeach
      @endif
   </table>
 </div>