routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('home', function () {
    return view('home');
});

Route::resource('pozivi', 'PoziviKontroler');




Route::resource('pitanjapoziv', 'PitanjaPoziviKontroler');





// Projekat rute


// Vrsi se filter pretraga projekata
Route::post('/projekatpretraga', 'ProjekatKontroler@pretragaProjakata');


Route::resource('projekat', 'ProjekatKontroler');


Route::resource('recenzent', 'RecenzentKontroler');

Route::resource('recenzentadmin', 'RecenzentAdminKontroler');

Route::resource('ocenjivanjeprojekta', 'RecenzentOcenjivanjeProjektaKontroler');

Route::resource('adminanketa', 'AdminAnketaKontroler');

Route::resource('recenzentanketa', 'RecenzentAnketaKontrolor');

Route::resource('adminobavestenja', 'AdminObavestenjaKontroler');

Auth::routes();

app/Projekat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Projekat extends Model
{
     protected $guarded = [];
     // Table Name
  protected $table = 'projekat';
  // Primary Key
  public $primaryKey = 'idProjekat';

  public function pozivProjekat()
    {
        return $this->belongsTo('App\Poziv', 'pozivi_idPoziv', 'idPoziv');
    }

    /**
     *
     */
    public function recenzents()
    {
      //  return $this->belongsToMany(Recenzent::class);
        return $this->belongsToMany('App\Projekat', 'projekat_recenzent', 'p_idProjekat', 'r_idRecenzent');
    }

    public function projekatRadi()
    {
        return $this->hasMany('App\ProjekatRecenzent', 'p_idProjekat', 'idProjekat');
    }
}

resources/views/projekat/admin_detalji_projekta.blade.php
<div class="row">
    <div id="proj"></div>
    <div class="offset-1 col-sm-5 col-11">
        <table class="table table-hover link1" style="margin-top:2px;">


            <tr>
                <td>Naziv projekta:</td>
                <td>{{$projekat->nazivProjekta}}</td>
            </tr>
            <tr>
                <td>Rukovodioc projekta:</td>
                <td>{{$projekat->rukovodiocProjekta}}</td>
            </tr>
            <tr>
                <td>Oblast projekta:</td>
                <td>{{$projekat->oblastProjekta}}</td>
            </tr>
            <tr>
                <td>Datum podnošenja</td>
                <td>{{$projekat->datumPodnosenja}}</td>
            </tr>

        </table>
    </div>
    <div class="offset-1 col-sm-5 col-11">
        <div>

              @if(isset($projekat))
                 <?php   $nazivDirektorijuma=$projekat->nazivProjekta;
               //   backshlesh
                $dirname = public_path('\uploads\\'.$nazivDirektorijuma);
                // Pojavljivale su se  .  i .. ispred svakog naziva fajla zato treba da se izbace
                $images = array_diff(scandir($dirname), array(".", ".."));
                ?>

                @foreach ($images as $slika)
                    @if(!empty($dirname))

                        <a  target="_blank" href="{{$dirname.'\\'.$slika}}">{{$slika}}</a>&nbsp;&nbsp;&nbsp;
                    @endif
                @endforeach
              @endif


        </div>
        <br>
        <br>
        <div>
            <form method="POST" action="{{ route('projekat.destroy', $projekat->idProjekat) }}">
        @csrf

            {{ method_field('delete') }}
            <button type="submit" class="btn dugme">Obrisi projekat</button>

            </form>
        </div>
        <br>
        <div>

            <a class="btn dugme" href="projekat/{{$projekat->idProjekat}}/edit">Promeni podatke</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="offset-1 col-5">
        <table class="table table-hover" style="margin-top:2px;">
            <tr><td><h5>Recezenti projekta:</h5></td></tr>
          @if(count($recenzenti)>0)
            @foreach($recenzenti as $r)
               @if($r!=null)
            <tr><td ><a href="">{{$r->ime." ".$r->prezime}}</a></td></tr>
               @endif
            @endforeach
            @endif
        </table>
    </div>
</div>
<div class="row">
  @if(isset($pitanja))
    @foreach($pitanja as $p)

        <div class="row">
            <div class="col-6">
                <textarea class="form-control" disabled>{{$p->pitanje}}</textarea>
        </div>


        <div class="col-6">
         @if(isset($ocena))
            @foreach($ocena as $o)

               @if($o->pitanjaPoziv_idPitanja==$p->idPitanja)


                <div class="row" >
                    <div class="col-4">
                        <textarea class="form-control" id="ocenaKomentar" disabled >{{$o->komentarOcene??""}}</textarea>
                    </div>
                    <div class="col-2">

                        <textarea class="form-control" id="ocena" disabled >{{$o->ocenaProjekta??""}}</textarea>

                    </div>
                    <div class="col-4">

                        {{$o->ime??""." ".$o->prezime??""}}

                    </div>

                </div>


                <br><br>


                   @elseif($o->pitanjaPoziv_idPitanja==$p->idPitanja)
                       <br><br>
                   @endif

            @endforeach
          @endif

        </div><br><br>
    </div>

@endforeach
    @endif
    <script>
    </script>
</div>

resources/views/projekat/admin_izmena_projekta.blade.php
@extends('basic')

@section('content')
    <div class="container">
           <span class="" role="alert">
              <strong>{{ $uspeh??"" }}</strong>
           </span>
        <div class="row justify-content-center">
            <div class="col-md-8">

                <form method="POST" enctype="multipart/form-data"  action="{{ route('projekat.update', $projekat->idProjekat) }}">
                    @csrf
                    {{ method_field('patch') }}

                    <div class="form-group row">
                        <label for="nazivProjekta" class="col-md-4 col-form-label text-md-right">{{ __('Naziv Projekta') }}</label>

                        <div class="col-md-6">
                            <input id="nazivProjekta" type="text"  class="form-control @error('nazivProjekta') is-invalid @enderror" name="nazivProjekta" value="{{ $projekat->nazivProjekta }}" required autocomplete="nazivProjekta" autofocus>

                            @error('nazivProjekta')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="rukovodiocProjekta" class="col-md-4 col-form-label text-md-right">{{ __('Rukovodioc Projekta') }}</label>

                        <div class="col-md-6">
                            <input id="rukovodiocProjekta" type="text"  class="form-control @error('rukovodiocProjekta') is-invalid @enderror" name="rukovodiocProjekta" value="{{ $projekat->rukovodiocProjekta }}" required autocomplete="rukovodiocProjekta" autofocus>

                            @error('rukovodiocProjekta')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>



                    <div class="form-group row">
                        <label for="NIORukovodioca" class="col-md-4 col-form-label text-md-right">{{ __('NIO Rukovodioca') }}</label>

                        <div class="col-md-6">
                            <input id="NIORukovodioca" type="text" class="form-control @error('NIORukovodioca') is-invalid @enderror" name="NIORukovodioca" value="{{ $projekat->NIOrukovodioc }}" required autocomplete="NIORukovodioca" autofocus>

                            @error('NIORukovodioca')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="zvanjeRukovodioca" class="col-md-4 col-form-label text-md-right">{{ __('Zvanje Rukovodioca') }}</label>

                        <div class="col-md-6">
                            <input id="zvanjeRukovodioca" type="text" class="form-control @error('zvanjeRukovodioca') is-invalid @enderror" name="zvanjeRukovodioca" value="{{ $projekat->zvanjeRukovodioca }}" required autocomplete="zvanjeRukovodioca" autofocus>

                            @error('zvanjeRukovodioca')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="angazovanjeRukovodioca" class="col-md-4 col-form-label text-md-right">{{ __('Angazovanje Rukovodioca') }}</label>

                        <div class="col-md-6">
                            <input id="angazovanjeRukovodioca" type="text" class="form-control @error('angazovanjeRukovodioca') is-invalid @enderror" name="angazovanjeRukovodioca" value="{{ $projekat->angazovanjeRukovodioca }}" required autocomplete="angazovanjeRukovodioca" autofocus>

                            @error('angazovanjeRukovodioca')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="oblastProjekta" class="col-md-4 col-form-label text-md-right">{{ __('Oblast Projekta') }}</label>

                        <div class="col-md-6">
                            <input id="oblastProjekta" type="text" class="form-control @error('oblastProjekta') is-invalid @enderror" name="oblastProjekta" value="{{ $projekat->oblastProjekta }}" required autocomplete="oblastProjekta" autofocus>

                            @error('oblastProjekta')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="odlukaProjekta" class="col-md-4 col-form-label text-md-right">{{ __('Odluka Projekta') }}</label>

                        <div class="col-md-6">
                            <input id="odlukaProjekta" type="text" class="form-control @error('odlukaProjekta') is-invalid @enderror" name="odlukaProjekta" value="{{ $projekat->odlukaProjekta }}" required autocomplete="odlukaProjekta" autofocus>

                            @error('odlukaProjekta')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="idPoziva" class="col-md-4 col-form-label text-md-right">{{ __('Poziv') }}</label>
                        <div class="col-md-6">
                            <select name="idPoziva"  class="btn btn-sm mr-5" )>
                                <option value="{{ $pozivSelected->idPoziv }}" selected>{{ $pozivSelected->naziv }}</option>
                                @foreach($sviPozivi as $s)
                                    <option value="{{$s->idPoziv}}">{{$s->naziv}}</option>
                                @endforeach
                            </select>
                            @error('idPoziva')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="dokument" class="col-md-4 col-form-label text-md-right">{{ __('Izmena dokumentacije') }}</label>
                        <div class="col-md-6 " name="dokument">
                            <input type="file"  id="dokument" name="dokument" >
                            @error('dokument')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>





                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Promeni') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/projekat/admin_pretraga_projekta.blade.php
@foreach($sviProjekti as $s)
    <div class="row card">
        <div>
            {{--<p><a class="link1" href="#" onclick="prikaziProjekat({{$s->idProjekat}}, {{$s->idPoziv}})">{{$s->nazivProjekta}} </a></p>--}}
            <p class="link1">{{$s->rukovodiocProjekta}}</p>
            <p class="link1">{{$s->oblastProjekta}}</p>
        </div>
    </div>
@endforeach

resources/views/projekat/admin_svi_projekti.blade.php
@extends('basic')
@section('content')
    <div class="row">
        <div class="ml-5 mt-5">

            {{--<form action="/projekatpretraga"  method="post">--}}
                @csrf
                <h4>Pretraga: </h4>
                <div class="form-group">
                    <input name="naziv" id="naziv" type="text" class="" placeholder="Pretraga po nazivu"/>


                    <select  class="" name="oblastProjekta" id="oblastProjekta">
                        <option value="" selected>Oblast projekta</option>
                        @foreach($sviProjekti as $s)
                            <option value="{{$s->oblastProjekta}}">{{$s->oblastProjekta}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group rowml-5">
                    <button type="submit" class="btn btn-small" name="pretraga" onclick="pretraga()">Pretraga</button>

                </div>
            {{--</form>--}}
        </div>
    </div>
    <div  class="row">

        <div class="offset-1 col-sm-2 col-11" id="pretraga">


            @foreach($sviProjekti as $s)
                <div class="row card" onclick="prikaziProjekat({{$s->idProjekat}})">
                    <div>
                        <p>{{$s->nazivProjekta}}</p>
                        <p class="link1">{{$s->rukovodiocProjekta}}</p>
                        <p class="link1">{{$s->oblastProjekta}}</p>
                    </div>
                </div>
            @endforeach


        </div>


        <div class="col-sm-8 col-12" style="margin-right: 5px;">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <div id="projekat">

            </div>
        </div>
    </div>

@endsection

resources/views/projekat/kreiraj_projekat.blade.php
@extends('layouts/app')
@section('content')

    <form action="/projekat" enctype="multipart/form-data" method="post">
        @csrf
       <div class="row">
        <div class=" offset -1 col-sm-5 col-12 ml-2">
                <div class="row">
                    <h1>Kreiraj projekat</h1>
                </div>
                <div class="form-group row">
                    <label for="nazivProjekta" class="col-md-4 col-form-label">Naziv Projekta</label>

                    <input id="nazivProjekta"
                           type="text"
                           class="form-control{{ $errors->has('nazivProjekta') ? ' is-invalid' : '' }}"
                           name="nazivProjekta"
                           value="{{ old('nazivProjekta') }}"
                           autocomplete="nazivProjekta" autofocus>

                    @if ($errors->has('nazivProjekta'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('nazivProjekta') }}</strong>
                        </span>
                    @endif
                </div>

                <div class="form-group row">
                    <label for="rukovodiocProjekta" class="col-md-4 col-form-label">Rukovodioc projekta</label>

                    <input id="rukovodiocProjekta"
                           type="text"
                           class="form-control{{ $errors->has('rukovodiocProjekta') ? ' is-invalid' : '' }}"
                           name="rukovodiocProjekta"
                           value="{{ old('rukovodiocProjekta') }}"
                           autocomplete="rukovodiocProjekta" autofocus>

                    @if ($errors->has('rukovodiocProjekta'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('rukovodiocProjekta') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group row">
                    <label for="NIORukovodioca" class="col-md-4 col-form-label">NIO Rukovodioca</label>

                    <input id="NIORukovodioca"
                           type="text"
                           class="form-control{{ $errors->has('NIORukovodioca') ? ' is-invalid' : '' }}"
                           name="NIORukovodioca"
                           value="{{ old('NIORukovodioca') }}"
                           autocomplete="NIORukovodioca" autofocus>

                    @if ($errors->has('NIORukovodioca'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('NIORukovodioca') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group row">
                    <label for="zvanjeRukovodioca" class="col-md-4 col-form-label">Zvanje Rukovodioca</label>

                    <input id="zvanjeRukovodioca"
                           type="text"
                           class="form-control{{ $errors->has('zvanjeRukovodioca') ? ' is-invalid' : '' }}"
                           name="zvanjeRukovodioca"
                           value="{{ old('zvanjeRukovodioca') }}"
                           autocomplete="zvanjeRukovodioca" autofocus>

                    @if ($errors->has('zvanjeRukovodioca'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('zvanjeRukovodioca') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group row">
                    <label for="angazovanjeRukovodioca" class="col-md-4 col-form-label">Angazovanje Rukovodioca</label>

                    <input id="angazovanjeRukovodioca"
                           type="text"
                           class="form-control{{ $errors->has('angazovanjeRukovodioca') ? ' is-invalid' : '' }}"
                           name="angazovanjeRukovodioca"
                           value="{{ old('angazovanjeRukovodioca') }}"
                           autocomplete="angazovanjeRukovodioca" autofocus>

                    @if ($errors->has('angazovanjeRukovodioca'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('angazovanjeRukovodioca') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group row">
                    <label for="oblastProjekta" class="col-md-4 col-form-label">Oblast projekta</label>

                    <input id="oblastProjekta"
                           type="text"
                           class="form-control{{ $errors->has('oblastProjekta') ? ' is-invalid' : '' }}"
                           name="oblastProjekta"
                           value="{{ old('oblastProjekta') }}"
                           autocomplete="oblastProjekta" autofocus>

                    @if ($errors->has('oblastProjekta'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('oblastProjekta') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group row">
                    <label for="odlukaProjekta" class="col-md-4 col-form-label">Odluka Projekta</label>

                    <input id="odlukaProjekta"
                           type="text"
                           class="form-control{{ $errors->has('odlukaProjekta') ? ' is-invalid' : '' }}"
                           name="odlukaProjekta"
                           value="{{ old('odlukaProjekta') }}"
                           autocomplete="odlukaProjekta" autofocus>

                    @if ($errors->has('odlukaProjekta'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('odlukaProjekta') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group row">
                    <select name="idPoziva" class="btn dugme" )>
                        @foreach($pozivi as $p)
                        <option value="{{$p->idPoziv}}">{{$p->naziv}}</option>
                       @endforeach
                    </select>
                </div>
        </div>


           <div class=" offset -1 col-sm-5 col-12 ml-5 mt-5 justify-content-center">
                   <h4>Dodavanje Projektne dokumentacije:</h4>

                    <input type="file" class="form-control-file" id="dokument" name="dokument" >

                    @if ($errors->has('dokument'))
                        <strong>{{ $errors->first('dokument') }}</strong>
                    @endif


                <div class="row pt-4">
                    <button class="btn btn-primary">Kreiraj</button>
                </div>
        </div>
        </div>
    </form>




@endsection

resources/views/projekat/recenzent_projekat_obrada.blade.php
<div class="row">

    <div class="offset-1 col-md-5 col-11 mt-5">
        <table class="table-hover link1" style="margin-top:2px;">

            <tr>
                <td>Naziv projekta:</td>
                <td>{{$projekat->nazivProjekta}}</td>
            </tr>
            <tr>
                <td>Rukovodioc projekta:</td>
                <td>{{$projekat->rukovodiocProjekta}}</td>
            </tr>
            <tr>
                <td>Oblast projekta:</td>
                <td>{{$projekat->oblastProjekta}}</td>
            </tr>
            <tr>
                <td>Datum podnošenja</td>
                <td>{{$projekat->datumPodnosenja}}</td>
            </tr>

        </table>
    </div>
    <div class="offset-1 col-md-5 col-11 mt-5">
        <h5 class="link1">Dokumentacija Projekta:</h5>
            @if(isset($projekat))
               <?php   $nazivDirektorijuma=$projekat->nazivProjekta;
             //   backshlesh
              $dirname = public_path('\uploads\\'.$nazivDirektorijuma);
              // Pojavljivale su se  .  i .. ispred svakog naziva fajla zato treba da se izbace
              $images = array_diff(scandir($dirname), array(".", ".."));
              ?>

              @foreach ($images as $slika)
                  @if(!empty($dirname))

                      <a  target="_blank" href="{{$dirname.'\\'.$slika}}">{{$slika}}</a>&nbsp;&nbsp;&nbsp;
                  @endif
              @endforeach
            @endif

    </div>
</div>
<br>
<hr>
<br>
<?php
$zakljucano = 0;
foreach($ocena as $o)
  {
   if($o->statusOcene=='zakljucana')
    {
       $zakljucano++;
    }
  }
  ?>
  <div class="row mt-5">
    @if($zakljucano==count($ocena))
    <form method="POST" enctype="multipart/form-data"  action="{{ route('ocenjivanjeprojekta.update', $projekat->idProjekat) }}">
        @csrf
        {{ method_field('patch') }}
       <div class="col-12 mt-3">
         <input type="hidden" name="projekatRadi" id ="projekatRadi" value="{{$radi->first()->id}}" />
         <input type="hidden" name="kraj" id ="kraj" value="zavrseno_ocenjivanje" />
         @if($radi->first()->stanjePrijave == "zavrseno_ocenjvanje")
         <p>Recenzija projekta je uspešno završena i predat je izveštaj.</p><br><br><hr>
         @else
         <button type="submit"  class="btn dugme btn-block">Predaj izvestaj</button>
         @endif
         <!-- <button class='btn dugme' onclick='predaj_izvestaj({{$projekat->idProjekat}})'>Predaj izvestaj</button> -->
        </div>
      </form>
    @endif
    @foreach($ocena as $o)
      @if(empty($o->idOcene))
         <div class="row form-group mt-5">
            <div class="col-md-4 col-sm-6 col-12 ">
                <textarea cols="200" class="form-control" disabled>{{$o->pitanje}}</textarea>
            </div>
            <div class="col-md-4 col-sm-6 col-12 ">
                 <textarea cols="100" class="form-control" id="ocena{{$o->idPitanja}}"></textarea>
             </div>
             <div class="col-md-2 col-sm-6 col-12 ">
             <select id="ocenaProjekta{{$o->idPitanja}}">
                @for($i=1; $i<=10; $i++)
                 <option value="<?php echo $i ?>"><?php echo $i ?></option>
                @endfor
             </select>
             </div>
             <div class="col-md-4 col-sm-6 col-12 mt-3">
                <input type="hidden" name="idProjekat" id ="idProjekat{{$o->idPitanja}}" value="{{$projekat->idProjekat}}" />
                <input type="hidden" name="projekatRadi" id ="projekatRadi{{$o->idPitanja}}" value="{{$radi->first()->id}}" />
                <button class='btn dugme btn-sm' onclick='dodavanje_ocene({{$o->idPitanja}})'>Unesi</button>
             </div>
         </div>
         <br><br>
       @endif
       @if(!empty($o->idOcene))
       <input type="hidden" name="idProjekat" id ="idProjekat{{$o->idPitanja}}" value="{{$projekat->idProjekat}}" />
       <input type="hidden" name="idProjekat" id ="idOcene{{$o->idPitanja}}" value="{{$o->idOcene}}" />
       <input type="hidden" name="zakljucavanje" id ="zakljucavanje{{$o->idPitanja}}" value="zakljucana" />
          <div class="row form-group mt-5">
             <div class="col-md-4 col-sm-6 col-12 ">
                 <textarea cols="200" class="form-control" disabled>{{$o->pitanje}}</textarea>
             </div>
            <div class="col-md-4 col-sm-6 col-12">
                  <textarea class="form-control" id="ocena{{$o->idPitanja}}"  <?= $o->statusOcene=="zakljucana"?"disabled":""?>>{{$o->komentarOcene}}</textarea>
            </div>
            <div class="col-md-4 col-sm-6 col-12">
            <select id="ocenaProjekta{{$o->idPitanja}}" <?=  $o->statusOcene=="zakljucana"?"disabled":""?>>
                 <option value="{{$o->ocenaProjekta}}" selected>{{$o->ocenaProjekta}}</option>
               @for($i=1; $i<=10; $i++)
                 <option value="<?php echo $i ?>"><?php echo $i ?></option>
               @endfor
            </select>
            </div>
          </div>
          @if($o->statusOcene!='zakljucana')
           <div class="row form-group">
               <div class="col-md-4 col-sm-6 col-12 mt-3">
                   <button class='btn dugme btn-sm' onclick='izmena_ocene({{$o->idPitanja}})'>Izmeni</button>
               </div>
               <div class="col-md-4 col-sm-6 col-12 mt-3">
                   <button class="btn dugme btn-sm" onclick='zakljucaj_ocenu({{$o->idPitanja}})'>Zaključaj</button>
               </div>
               <div class="col-md-4 col-sm-6 col-12 mt-3">
                   <button class="btn dugme btn-sm" onclick='obrisi_ocenu({{$o->idPitanja}})'>Obrisi</button>
               </div>
            </div>
            <br><br>
          @endif
        @endif
      @endforeach
  </div>

resources/views/projekat/recenzent_projekti.blade.php
@extends('basic')
@section('content')
    <div class="row">

        <div class="col-sm-3 col-12">

            @foreach($mojProjekat as $m)
                <div class="row card card-body mb-2 ml-1" onclick="prikaziMojProjekat({{$m->idProjekat}})">
                    <div>
                        <p>{{$m->nazivProjekta}}</p>
                        <p class="link1">{{$m->rukovodiocProjekta}}</p>
                        <p class="link1">{{$m->oblastProjekta}}</p>
                    </div>
                </div>
            @endforeach


        </div>
        @if (session('status'))
            <script>
            alert("{{session('status')}}");
            </script>

        @endif

        <div class="col-sm-9 col-12">

            <div id="projekat">

            </div>
        </div>
    </div>

@endsection