routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('home', function () {
    return view('home');
});

Route::resource('pozivi', 'PoziviKontroler');




Route::resource('pitanjapoziv', 'PitanjaPoziviKontroler');





// Projekat rute


// Vrsi se filter pretraga projekata
Route::post('/projekatpretraga', 'ProjekatKontroler@pretragaProjakata');


Route::resource('projekat', 'ProjekatKontroler');


Route::resource('recenzent', 'RecenzentKontroler');

Route::resource('recenzentadmin', 'RecenzentAdminKontroler');

Route::resource('ocenjivanjeprojekta', 'RecenzentOcenjivanjeProjektaKontroler');

Route::resource('adminanketa', 'AdminAnketaKontroler');

Route::resource('recenzentanketa', 'RecenzentAnketaKontrolor');

Route::resource('adminobavestenja', 'AdminObavestenjaKontroler');

Auth::routes();

app/Recenzent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recenzent extends Model
{
    protected $guarded = [];
    // Table Name
    protected $table = 'recenzenti';
    // Primary Key
    public $primaryKey = 'idRecenzent';

    public function useri()
    {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }

    public function oblastiStrucnosti()
    {
        return $this->belongsTo('App\OblastStrucnosti', 'oblastStrucnosti_id', 'id');
    }

    /**
     *
     */
    public function projekats()
    {
       // return $this->belongsToMany(Projekat::class);
        return $this->belongsToMany('App\Projekat', 'projekat_recenzent', 'r_idRecenzent', 'p_idProjekat')->withPivot('rokZaIzvestaj');
    }

    public function anketas()
    {
       // return $this->belongsToMany(Projekat::class);
        return $this->belongsToMany('App\Anketa', 'anketa_recenzent', 'r_idRecenzent', 'a_idAnketa')->withPivot('idAnketuRadi', 'status')->withTimestamps();
    }

    public function mojaObavestenja()
    {
      return $this->belongsToMany('App\Obavestenja', 'obavestenja_recenzent', 'r_idRecenzent', 'o_idObavestenja')->withPivot('idObavRec')->withTimestamps();
    }
}

resources/views/recenzent/admin_recenzent_detalji.blade.php
<div class="row ml-2">
    <div id="proj"></div>
    <div class="offset-1 col-sm-5 col-11">
        <table class="table table-hover link1" style="margin-top:2px;">


            <tr>
                <td>Ime i prezime:</td>
                <td>{{$recenzent->ime}} {{$recenzent->prezime}}</td>
            </tr>
            <tr>
                <td>NIO:</td>
                <td>{{$recenzent->NIO}}</td>
            </tr>
            <tr>
                <td>Naucno Zvanje:</td>
                <td>{{$recenzent->naucnoZvanje}}</td>
            </tr>
            <tr>
                <td>Angazovanje:</td>
                <td>{{$recenzent->angazovanje}}</td>
            </tr>

        </table>
    </div>
    <div class="offset-1 col-sm-5 col-11">


        <?php   $nazivDirektorijuma=$korIme;
        //   backshlesh
        $dirname = public_path('\recenzenti\\'.$nazivDirektorijuma);
        // Pojavljivale su se  .  i .. ispred svakog naziva fajla zato treba da se izbace
        $images = array_diff(scandir($dirname), array(".", ".."));
        ?>

        @foreach ($images as $slika)
            @if(!empty($dirname))

                <a  target="_blank" href="{{$dirname.'\\'.$slika}}">{{$slika}}</a>
            @endif
        @endforeach

    </div>
</div>
    <div class="row mb-3 ml-2">


            <h5>Angazovanje recenzenta:</h5><br>
            @if(count($angazovanje)>0)
            @foreach($angazovanje as $a)

                Naziv projekta: {{$a->nazivProjekta}}<br>
                Rok za izveštaj: {{$a->pivot->rokZaIzvestaj}}

            @endforeach
            @endif

    </div>
    <div class="row mb-3 ml-2">
        <h5>Dodela projekta: </h5>


        <select id="idProjekat">
            <option value="Izaberi projekta" selected></option>
            @if(count($projekti)>0)
                @foreach($projekti as $p)

                    <option value="{{$p->idProjekat}}">{{$p->nazivProjekta}}</option>
                @endforeach
            @endif
        </select>

        <input type="date" id="rokZaIzvestaj" />
        <input type="hidden" name="idKorisnik" id ="idRecenzent" value="{{$recenzent->idRecenzent??""}}" />&nbsp;&nbsp;&nbsp;




        <button type="submit" class='btn mt-2' onclick='dodela_projekta()'>Dodaj</button>


    </div>

    <div class="row ml-2">


        @if($recenzent->stanjePrijave!='registrovan')
            <h5>Status prijave: </h5>&nbsp;&nbsp;
            <input type="hidden"  value="{{$recenzent->statusPrijave}}" disabled />
            <select id="status">
                <option>razmatra_se</option>
                <option>registrovan</option>
            </select>&nbsp;&nbsp;&nbsp;
            <input type="hidden" name="idKorisnik" id ="idRecenzent" value="{{$recenzent->idRecenzent}}" />
            <button class='btn' onclick='statusPrijave()'>Promeni</button>

        @endif
    </div>

resources/views/recenzent/admin_svi_recenzenti.blade.php
@extends('basic')
@section('content')

    <div  class="row">

        <div class="offset-1 col-sm-2 col-11" id="recenzenti">

            @if(count($sviRecenzenti)>0)
                @foreach($sviRecenzenti as $s)
                    <div class="row card card-body mb-2" onclick="prikaziRecenzenta({{$s->idRecenzent}})">
                        <div>
                            <p>{{$s->nazivProjekta}}</p>
                            <p class="link1">{{$s->ime}} {{$s->prezime}}</p>
                            <p class="link1">{{$s->naucnoZvanje}}</p>
                        </div>
                    </div>
                @endforeach
            @endif

        </div>


        <div class="col-sm-8 col-12" style="margin-right: 5px;">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <div id="projekat">

            </div>
        </div>
    </div>

@endsection

resources/views/recenzent/izmena_podataka.blade.php
@extends('basic')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">

                <form method="POST" enctype="multipart/form-data"  action="{{ route('recenzent.update', $recenzent->idRecenzent) }}">
                    @csrf
                    {{ method_field('patch') }}

                    <div class="form-group row">
                        <label for="ime" class="col-md-4 col-form-label text-md-right">{{ __('Ime') }}</label>

                        <div class="col-md-6">
                            <input id="ime" type="text"  class="form-control @error('ime') is-invalid @enderror" name="ime" value="{{ $recenzent->ime }}" required autocomplete="ime" autofocus>

                            @error('ime')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="prezime" class="col-md-4 col-form-label text-md-right">{{ __('Prezime') }}</label>

                        <div class="col-md-6">
                            <input id="prezime" type="text"  class="form-control @error('prezime') is-invalid @enderror" name="prezime" value="{{ $recenzent->prezime }}" required autocomplete="prezime" autofocus>

                            @error('prezime')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>



                    <div class="form-group row">
                        <label for="nacionalnost" class="col-md-4 col-form-label text-md-right">{{ __('Nacionalnost') }}</label>

                        <div class="col-md-6">
                            <input id="nacionalnost" type="text" class="form-control @error('nacionalnost') is-invalid @enderror" name="nacionalnost" value="{{ $recenzent->nacionalnost }}" required autocomplete="nacionalnost" autofocus>

                            @error('nacionalnost')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="zemlja" class="col-md-4 col-form-label text-md-right">{{ __('Zemlja') }}</label>

                        <div class="col-md-6">
                            <input id="zemlja" type="text" class="form-control @error('zemlja') is-invalid @enderror" name="zemlja" value="{{ $recenzent->zemlja }}" required autocomplete="zemlja" autofocus>

                            @error('zemlja')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="NIO" class="col-md-4 col-form-label text-md-right">{{ __('NIO') }}</label>

                        <div class="col-md-6">
                            <input id="NIO" type="text" class="form-control @error('ime') is-invalid @enderror" name="NIO" value="{{ $recenzent->NIO }}" required autocomplete="NIO" autofocus>

                            @error('NIO')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="trenutnaFirma" class="col-md-4 col-form-label text-md-right">{{ __('Trenutna Firma') }}</label>

                        <div class="col-md-6">
                            <input id="trenutnaFirma" type="text" class="form-control @error('trenutnaFirma') is-invalid @enderror" name="trenutnaFirma" value="{{ $recenzent->trenutnaFirma }}" required autocomplete="trenutnaFirma" autofocus>

                            @error('trenutnaFirma')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="naucnoZvanje" class="col-md-4 col-form-label text-md-right">{{ __('Naucno zvanje') }}</label>

                        <div class="col-md-6">
                            <input id="naucnoZvanje" type="text" class="form-control @error('naucnoZvanje') is-invalid @enderror" name="naucnoZvanje" value="{{ $recenzent->naucnoZvanje }}" required autocomplete="naucnoZvanje" autofocus>

                            @error('naucnoZvanje')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="angazovanje" class="col-md-4 col-form-label text-md-right">{{ __('Angazovanje') }}</label>

                        <div class="col-md-6">
                            <input id="angazovanje" type="text" class="form-control @error('angazovanje') is-invalid @enderror" name="angazovanje" value="{{ $recenzent->angazovanje }}" required autocomplete="angazovanje" autofocus>

                            @error('angazovanje')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="oblastiStrucnosti" class="col-md-4 col-form-label text-md-right">{{ __('Oblasti Strucnosti') }}</label>
                        <div class="col-md-6">
                            <select name="oblastiStrucnosti"  class="btn btn-sm mr-5" )>
                                <option value="" selected>Oblasti strucnosti</option>
                                @foreach($oblasti as $o)
                                    <option value="{{$o->id}}">{{$o->naziv}}</option>
                                @endforeach
                            </select>
                            @error('oblastiStrucnosti')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="telefon" class="col-md-4 col-form-label text-md-right">{{ __('Telefon') }}</label>

                        <div class="col-md-6">
                            <input id="telefon" type="text" class="form-control @error('telefon') is-invalid @enderror" name="telefon" value="{{ $recenzent->telefon }}" required autocomplete="telefon" autofocus>

                            @error('telefon')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="adresa" class="col-md-4 col-form-label text-md-right">{{ __('Adresa') }}</label>

                        <div class="col-md-6">
                            <input id="adresa" type="text" class="form-control @error('adresa') is-invalid @enderror" name="adresa" value="{{ $recenzent->adresa }}" required autocomplete="adresa" autofocus>

                            @error('adresa')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="dokument" class="col-md-4 col-form-label text-md-right">{{ __('Promena Biografije') }}</label>
                        <div class="col-md-6 " name="dokument">
                            <input type="file"  id="dokument" name="dokument" >
                            @error('dokument')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="vebStranica" class="col-md-4 col-form-label text-md-right">{{ __('Veb Stranica') }}</label>

                        <div class="col-md-6">
                            <input id="vebStranica" type="text" class="form-control @error('vebStranica') is-invalid @enderror" name="vebStranica" value="{{ $recenzent->vebStranica }}" required autocomplete="vebStranica" autofocus>

                            @error('vebStranica')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Promeni') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection